### PR TITLE
Attempt to migrate to CircleCI version 2.

### PR DESCRIPTION
**Pull request by tttppp**
CircleCI are sunsetting CircleCI 1.0 on August 31st, 2018.  I've tried to follow the migration instructions here: https://circleci.com/docs/2.0/migrating-from-1-2/

### CODE REVIEW

**Comment by zond** [comment]
These CI things usually require tens of commits before they work properly, so just keep committing and pushing until you get it right (if you have the stamina :) - no need for review I think (it didn't work before anyway, did it?)

**Comment by tttppp** [comment]
Ah, OK. I thought this was used for the release. I wanted to push something and see if it built.

**Comment by zond** [comment]
Oh, right - I mistook this for the server project....

Yeah, it's used for the release, but I still think you should just go ahead and retry until it works, because it's not critical if it fails - and waiting for review will be a pain :)

**Comment by tttppp** [comment]
Ok! I ran out of time now, but I'll try another time. It didn't seem to kick off a build weirdly, so I guess something's missing.

**Comment by zond** [comment]
Hm, strange. Well good luck :)

On Feb 28, 2018 17:36, "tttppp" <notifications@github.com> wrote:

Ok! I ran out of time now, but I'll try another time. It didn't seem to
kick off a build weirdly, so I guess something's missing.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/zond/android-diplicity/pull/71#issuecomment-369316452>,
or mute the thread

**Pull request closed without merging**
