### PR TITLE
Added a toggle-map icon to the chat view. Doesnt work :/

### PR DESCRIPTION
**Pull request by zond**

### CODE REVIEW

**Comment by zond** [comment]
@tttppp are you good at Android event handling?

For some reason, when I create the MapView with visibility `GONE` it doesn't actually load the URL.

I can fix that (a bit ugly) by forcing a `mapView.draw()` in PressActivity, which makes the map appear.

But then I notice that it doesn't get any touch events, so I can't submit orders, pan, zoom, or use the buttons.

Any idea why? I'm flummoxed.

**Comment by zond** [comment]
Ah, with ViewSwitcher I got it working!

**Comment by tttppp** [comment]
Ah good- already fixed! I only just got around to looking at it - sorry. Great feature BTW!

**Comment by zond** [comment]
Haha yeah, best kind of bug - that gets fixed without your input :D

**Pull request merged**
