### PR TITLE
Generated game name

### LINKED ISSUE #48: Generated game names
People are generally very bad at coming up with interesting, or worthwhile game names. Most names fall into a few categories:
 * Information duplicated by the listing page (e.g. the turn length, or variant name)
 * Random keyboard bashing or a random word
 * Nothing at all (the empty string)

IMO it would be nice to suggest a randomly generated title for the game, so that they are more easily found in a list of games and remembered.  I propose using the following structure:

The [synonym of battle] for the [adjective] [noun]

If people don't want to think of a name then this will make their game easily identifiable. If people want to change the game name then they're free to.

### PR DESCRIPTION
**Pull request by tttppp**
Fixes #48.

Assuming the user doesn't enter a game name then this makes one for them. It uses the form "The [battle] for the [adjective] [prize]" where [battle] indicates the phase length, [adjective] indicates some other defining game setting and [prize] is just a random noun.

I'm unable to test the final code, but I did test it with some workarounds (see the "hacks" commit and revert).  I'm happy to rebase to remove the hacks from the commit history if you're bothered by it. I thought I might want to use the same workaround again in future.

### CODE REVIEW

**Comment by zond** [comment]
I'm only able to look at this on a phone, and am unable to get a proper sense for what the hacky workaround actually did. Since you removed it it doesn't really matter, but could you describe it just to sate my curiosity? :)

Other than that it looks good. Merge when happy!

When the auto build produces a new version, you can test it yourself, and if you like it I can push it to Play Store.

**Comment by tttppp** [comment]
The hacks were all around not loading the user stats from the server.  This doesn't work with fake users (I think it needs access to the Google identity service?) and I couldn't use the real Diplicity URL (as I don't have the application key).

The easiest option was to use the real server, but ignore any errors, so I also had to hard code a list of variants. GitHub displays far more diff for that commit than there actually is, because I also changed the indentation.  With a decent diff viewer it looks a lot more sane.

I didn't realise I can download the apk from CircleCI (you have to have an account with them to do so). I've done that now and will try testing it!

**Comment by tttppp** [comment]
Hooray! It works. Testing using the release APK makes things a lot easier.  Please push to the Play Store when ready - thanks!

**Comment by zond** [comment]
Ok, I'll push!

Note that it's definitely intended for fake users to be able to do everything real users can - otherwise testing with them is too hard. So a patch that makes fake users work properly in a way that conforms work how fake users are otherwise treated would be a good thing :)

**Comment by zond** [comment]
Ok, rollout is started!

**Comment by zond** [comment]
Aaand it's live!

**Comment by tttppp** [comment]
Ok, I'll have to reproduce and put the stack trace in an issue. I remember seeing a problem with null in a url where it's expecting the user id.

Thanks for putting it live!

**Comment by zond** [comment]
Cool! Thanks for adding stuff!

**Pull request merged**
