### PR TITLE
Added NoMerge to all games where the user edited the Desc field.

### PR DESCRIPTION
**Pull request by zond**

### CODE REVIEW

**Comment by zond** [comment]
@tttppp Could you check if this seems OK - I still don't fully understand your code where you manage the generated name for Desc :D

**Comment by tttppp** [comment]
I still didn't get around to loading this up ob a proper screen, so I thought I'd just write a note to explain the game name choosog code.

**Comment by tttppp** [comment]
*choosing

The aim was to have a seed stored while the new game dialog is open, so that the user can change a few fields and see various potential game names, but they can't easily cycle through all the potential game names for a given set of parameters. I didn't want everyone picking 'banana' as their game prize just because it was the funniest.

Other than that I think the code is quite simple. There are some lists of strings, and the code uses a random number modulo the list length to pick the output. Possibly I might have done something to avoid e.g. 'banana' always matching up with 'blue,  but maybe I just did that by having coprime list lengths.

**Comment by zond** [comment]
Thanks for the explanation!

My code seems to work, anyway, so I'm happy.

**Pull request merged**
