### PR TITLE
Implements #47: Variant info view

### PR DESCRIPTION
**Pull request by tttppp**
Add a new view so that players can see the rules for different variants.

### CODE REVIEW

**Comment by tttppp** [comment]
The view is always available (like the map) so that players can use the rules to decide if they want to play.

screenshot_2017-09-11-07-17-55

screenshot_2017-09-11-07-17-59

**Comment by tttppp** [comment]
Great! I added some labels for the fields and a bit of logic about hiding empty fields.  Tested the CircleCI build and it looks good to me.

**Comment by zond** [comment]
Cool, feel free to roll it out :)

**Comment by tttppp** [comment]
Annoyingly I can't release it.  Tried to do that today, but Google now requires additional information to publish an app.  Please can you fill in the "Primarily Child-Directed" field under "Pricing & Distribution" (set it to false, as the app isn't primarily targeted at children).  Thanks!

I get "You currently don't have the necessary rights to edit this app. Please ask the account owner to grant you access. The contact email address is [your email address]."

**Comment by zond** [comment]
OK, I updated the "Primarily Child-Directed" field to "No", and gave you
more ACLs to the Diplicity app. See if it works now?

**Comment by tttppp** [comment]
Great, thanks. The app is now available as a beta (to 51 users!), and I also have permission to fix the Pricing & Distribution in case Google adds any new mandatory fields. I'll roll the beta out to production in a few days.

Thanks!

**Comment by zond** [comment]
Great!

**Pull request merged**
